modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="cubic_fruits"
version="0.1.0"
displayName="Cubic Fruits"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cubic-fruits"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MacToxa"
description=" Blox Fruits & One Piece stuff in MC"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.cubic_fruits]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cubic_fruits]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.cubic_fruits]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration